### Paths ###
data_path: D:\Projects\mri2pet\data
checkpoint_dir: D:\Projects\mri2pet\checkpoints\debug
res_dir: D:\Projects\mri2pet\results

### Model ###
input_nc: 1
output_nc: 1
ngf: 64
ndf: 64

### Training ###
resume: false
epochs: 200
start_epoch: 0
batch_size: 8
patch_size: [64, 64, 64]
optimizer: 'adam'
scheduler: 'lr'
num_workers: 4
init_type: 'normal'
lr: 0.0002
earlystop: true
save_pariod: 20
niter_decay: 20

### Augmentation ###
transforms: ['Augmentation', 'RandomCrop']


device: cuda



